eth-protocol-fellows/protocol-studies

docs/eps/week0.md

There were no resources for me to look at for Pre-reading. This hopefully can help future readers if they don't know where to begin. 
Cryptography - links to the same pdf in /docs/wiki/Cryptography/intro.md
Two other sources are youtube videos which have better visuals for understanding

Add resources for week 0 pre readings

---

docs/eps/intro.md
docs/eps/week0.md
docs/eps/week1.md

Hi everyone! While reading the docs in preparation for tomorrow's session, I fixed a few typos.

✏️ Fix a few typos

---

docs/eps/week1.md

Update the link for annotated spec

---

docs/eps/week2.md

Hey this is roughly what I plan to talk about next week! PTAL and let me know if it seems reasonable. Trying to keep the reading light, but please please review the documents I listed:
* https://ethereum.org/developers/docs/nodes-and-clients
* https://cs251.stanford.edu/lectures/lecture7.pdf
It's not much, but will help you have a good foundation for the discussion on Monday :)

Add week 2 reading and outline

---

docs/eps/week2.md

Added a link to a Dan Boneh lecture that accompanies the "Ethereum: mechanics" slides. I figured it may be useful enough for other people.

Added a link to a Dan Boneh lecture that accompanies the "Ethereum: mechanics" slides

---

docs/eps/week1.md

devcon link lead to 404 page. replaced with working archive page

fix broken link to working link

---

docs/contributing.md

Technical writing can sometimes be overwhelming. I have linked to a great lecture on getting started.

🔗 Link to get started with writing

---

docs/eps/week2.md

Added week 2 written [summary link](https://ab9jvcjkej.feishu.cn/docx/BRDdd8kP9o00a2x6F4scRo0fnJh) below the video

Added week 2 written summary

---

docs/eps/week0.md

Fixed week0 embed stream URL

---

docs/_sidebar.md
docs/wiki/CL/overview.md

Introduces an overview page for consensus layer. Documents the links shared in discord during week3 lecture.

✨ Consensus layer overview

---

notes/Chloe_notes.md

Great hangout session today! Lots of interesting topics discussed with bunch of links mentioned. Briefly summerized in my note and shared here for reference.

Hangout chat notes by Chloe

---

notes/gorondan.md

notes GoronDan

---

docs/eps/week3.md

Suggesting a material that I found very useful when learning PoS.

Adding a useful reading material about PoS

---

docs/wiki/CL/overview.md

- 🐞Fixes link to GHOST paper.
- ✨ 3 new resources added.

🔗 Updates to Consensus resources

---

docs/wiki/testing/overview.md

Resources discussed in Week 4 lecture.

🔗 Testing resources

---

.gitignore
docs/_sidebar.md
docs/topics.md
docs/wiki/EL/JSON-RPC.md

JSON-RPC specs section added. Included some method lists and a couple of tooling examples of how to use them through curl and axios (js/ts)

Issue/85: JSON-RPC specs section closes #85

---

docs/wiki/protocol/Validator.md
docs/wiki/protocol/transaction.md

I've prepared this short and smart guide.Please comment

Transaction anatomy documentation

---

docs/_sidebar.md
docs/wiki/research/Beacon Chain Upgrades.md

added PoS-design folder and files to /research and _sidebar

added PoS-design folder and files to /research and _sidebar

---

notes/gorondan_MVEls_notes.md

Goron Dan - notes on Minimum Viable Enshrinement of Liquid Staking - a humble proposal

notes on Minimum Viable Enshrinement of Liquid Staking

---

docs/eps/intro.md

added Francesco D'Amato github profile

added Francesco D'Amato github profile

---

docs/wiki/EL/precompiled-contracts.md

This PR addresses feedback from  [this discussion.](https://github.com/eth-protocol-fellows/protocol-studies/pull/106#discussion_r1531862227)

✨ feat(EL): precompile security

---

notes/steven_notes/weekly_updates_1.md

Document my first weekly updates about EPF study

weekly updates #1

---

docs/wiki/Cryptography/KZG.md

I am working on the KZG commitment scheme. My goal is to write a self-containing wiki page for KZG so that beginners and intermediate skilled audience can read it and understand it. 
Why we need to learn KZG:
- Modern ZKSNARK = Functional Commitment Scheme + Compatible Interactive Oracle Proof (IOP)
- Ethereum Danksharding
- Other important Cryptography and Blockchain applications to preserve privacy
I will derive KZG by hands for a small finite field to visualize all the math happening behind KZG. This can understand KZG protocol flow.
https://github.com/thogiti/protocol-studies/blob/scaling/docs/wiki/Cryptography/KZG.md

KZG Polynomial Commitment Scheme

---

docs/eps/week3.md
docs/eps/week4.md

Week 3 CL overview notes: https://ab9jvcjkej.feishu.cn/docx/X7Ard9UlPoj2lmxKMvucfNubnTb
Week 4 Testing & Security notes: https://ab9jvcjkej.feishu.cn/docx/R1IOdEkDxoiNNHxvA6sclfITnLB

Add written notes for week 3 and week 4

---

docs/readme.md

discord link expired

---

docs/eps/week0.md

Hi guys, found an incorrect link, very tiny fix, thanks.

Fix the incorrect link

---

docs/eps/intro.md
wordlist.txt

🧹 chore(Intro): Important links

---

notes/steven_notes/PBS.md
notes/steven_notes/weekly_updates_2.md
wordlist.txt

My weekly updates 2 contains study notes regarding PBS and Portal Network

weekly updates #2

---

docs/wiki/protocol/data-structures.md
wordlist.txt

🧹 chore(Data structures): Add a new resource link, markdown clean up

---

docs/eps/week9-dev.md

This PR updates the week 9 talk contents, adding information such as preparation and outline

update week 9

---

wordlist.txt

Added missing words to wordlist coming from week9 doc

---

docs/eps/week5.md

update new links https://domothy.com/roadmap/

the domothy links error

---

notes/wiki_contributors_meeting/2024-04-18_kickoff_call.md
wordlist.txt

Please review if I have misinterpreted anything.

✨ feat: Meeting #1 notes

---

docs/wiki/research/PBS/ePBS.md

- [ x] Describe your changes, substitute this text with the information : added Roadmap Tracker artifact to ePBS wiki page
- [x ] If you are touching an existing piece of content, ask the original creator for review

added Roadmap Tracker artifact to ePBS wiki page

---

docs/eps/week3.md
docs/eps/week4.md

Find some tiny typo when learning. Thanks.

Fix incorrect week number

---

wordlist.txt

typos fixed

---

docs/_sidebar.md
wordlist.txt

Fixed missing link to KZG page in the sidebar

---

docs/_sidebar.md
docs/wiki/dev/cs-resources.md
wordlist.txt

✨ feat(Development): CS Resources

---

docs/contributing.md
docs/wiki/research/Preconfirmations/BasedSequencingPreconfs.md
docs/wiki/research/Preconfirmations/Preconfirmations.md

🧹 chore: Broken links

---

wordlist.txt

typos for wordlist is fixed

---

docs/wiki/EL/RLP.md

Updated after the review

---

docs/eps/intro.md

✨ feat: Wrap up

---

notes/wiki_contributors_meeting/2024-05-02_release_plan.md
wordlist.txt

✨ feat: Meeting #2 notes

---

docs/wiki/CL/merkleization.md

Updated for the suggestions after the review by Mario.

---

docs/_sidebar.md

Fixed the sidebar links, removed /docs/

---

docs/wiki/epf.md

fixed small typo

---

docs/_sidebar.md
docs/wiki/epf.md
docs/wiki/research/roadmap.md

* updated sidebar to fix eps.wiki hook on eODS page
* fixed roadmap img path for eps.wiki routing

2 wiki fixes 

---

docs/eps/intro.md

small typo fix

---

docs/wiki/research/PBS/mev-boost.md

Change wording for builders

---

docs/wiki/research/PBS/ePBS.md

Edited ePBS article after feedback

---

docs/wiki/testing/incidents.md

Adding some incidents

---

docs/eps/week1.md

fix missing word

---

docs/eps/week0.md

add a cryptography link

---

docs/contributing.md

add links to mirrors

---

docs/wiki/pectra-faq.md

correction: effective balance increments

---

docs/assets/css/custom.css

fix: fixing the sidebar

---

docs/wiki/CL/cl-architecture.md

These URL errors will cause the page to jump to a 404 error page.

fixed cl-architecture url

---

docs/eps/intro.md

Fixed the wrong week link

---

docs/eps/intro.md
docs/eps/week10-dev.md
docs/eps/week4.md
docs/readme.md
docs/wiki/EL/el-clients.md
docs/wiki/EL/transaction.md
docs/wiki/dev/core-development.md
docs/wiki/research/PBS/ET.md

fix: typos

---

docs/eps/nodes_workshop.md

Update broken link on nodes_workshop.md

---

docs/wiki/EL/el-clients.md

wiki link fixed

---

.github/workflows/broken-links.yml

✨ feat: CI - Broken links

---

docs/eps/intro.md
docs/eps/presentations/week2_notes.md
docs/eps/schedule.md
docs/eps/week0.md

docs/eps/intro.md
first 2 weeks - the first 2 weeks 
are few - are a few
`add article`
docs/eps/presentations/week2_notes.md
sstorge - storage `fix typo`
docs/eps/schedule.md
excercices - exercises `fix typo`
docs/eps/week0.md
answer - answered  `correction`

fix spelling issues 

---

docs/eps/day16.md

Update day 16

---

docs/eps/day17.md

Update lecture 17 about EVM

---

docs/_sidebar.md
docs/eps/day17.md
docs/eps/presentations/week2_notes.md
docs/wiki/EL/el-clients.md
docs/wiki/EL/eof.md
docs/wiki/research/PBS/pbs.md
wordlist.txt

Adds an EOF placeholder + some  fixes to minor typos

Add EOF stub

---

docs/eps/day16.md
docs/eps/day17.md

Youtube lecture recording embed links are fixed

fix: Youtube embed links for lecture 16 and 17

---

docs/eps/intro.md

Update intro.md dapplion link

---

docs/eps/day19.md
docs/wiki/dev/cs-resources.md

At [Distributed systems and blockchain](https://epf.wiki/#/wiki/dev/cs-resources?id=distributed-systems-and-blockchain)
[The Byzantine Generals Problem](https://people.eecs.berkeley.edu/~luca/cs174/byzantine.pdf)
This no longer provides the resource.
The link is updated to : 
https://lamport.azurewebsites.net/pubs/byz.pdf
https://github.com/eth-protocol-fellows/protocol-studies/blob/main/docs/wiki/dev/cs-resources.md#distributed-systems-and-blockchain

changed the link for Byzantine Generals Problem resource

---

docs/eps/day20.md

updating outline and resources for my Monday presentation

Day 20: validator architecture  resource update

---

docs/eps/week6-research.md

Added the link to PeerDAS to the Lec 11 page of DAS by Dankrad

Added a resource in the Lec 11 to EPFWiki's PeerDAS page

---

docs/eps/day22.md

Add a link to a Lighthouse blog post about Milhouse and tree-states, in preparation for my talk on CL data structures.

Add Lighthouse pre-reading for CL data structures

---

docs/eps/day22.md

Added the yt lecture link by Michael Sproul to the wiki page of Day 22 and also the embed

added lecture link and yt embed of the lecture by michael sproul to the wiki page of Day 22

---

docs/wiki/EL/data-structures.md

- added a description for the World State Trie

chore: add world state trie docs

---

docs/eps/day17.md
docs/eps/day19.md
docs/eps/day20.md
docs/eps/day21.md
docs/eps/day22.md
docs/eps/day23.md
docs/eps/day24.md
docs/wiki/EL/data-structures.md
docs/wiki/EL/eof.md
docs/wiki/EL/evm.md
wordlist.txt

As mentioned in #388, spellcheck is broken. This PR cleans up the content to get spellcheck working again using the new `<name>` tag where required.

✨ feat: chore: Unclog spellcheck

---

.github/workflows/spell-check.yml
docs/wiki/epf.md

The spellcheck ci comment had a bug causing it to fail. This PR fixes it.
I have tested the spell check by creating a [test PR and it works fine.](https://github.com/eth-protocol-fellows/protocol-studies/pull/420#issuecomment-2791541459)

🐞 fix: Spell check comment

---

docs/_sidebar.md
docs/eps/intro.md
docs/wiki/CL/merkleization.md
docs/wiki/dev/pm.md
docs/wiki/research/scaling/scaling.md

chore: Add missing EPS lectures + minor styling changes

---

docs/_sidebar.md
docs/eps/day23.md
docs/eps/day24.md
docs/wiki/EL/data-structures.md

fix: Minor styling fixes

---

docs/wiki/EL/JSON-RPC.md
docs/wiki/EL/el-architecture.md
wordlist.txt

- Updated method descriptions for key Engine API calls
- Added status response explanations (VALID, INVALID, SYNCING, ACCEPTED)
- Documented capability exchange (engine_exchangeCapabilities) during startup
- Expanded validator flow: fork choice updates, payload building, and validation

chore: engine api updates

---

docs/wiki/CL/cl-clients.md

This PR fixes all the Lighthouse broken links.

Fix Lighthouse broken links

---

docs/wiki/EL/data-structures.md

Added some resources for patricia trie

🧹 chore: trie resources

---

docs/wiki/CL/cl-specs.md

Adding a summary of how the CL specs work with some of its components including types, containers, presets etc.

Add CL specs summary

---

docs/wiki/research/Preconfirmations/BasedSequencingPreconfs.md

Hey team—noticed a dead link, replaced it with a working URL
https://docs.zksync.io/zk-stack/components/shared-bridges.html - old
https://docs.zksync.io/zksync-protocol/contracts/l1-contracts/shared-bridges - new

fix dead links BasedSequencingPreconfs.md

---

docs/wiki/pectra-faq.md

Fix bare URL lints

---

docs/wiki/CL/overview.md

Update CL Overview with MaxEB
