eth-protocol-fellows/protocol-studies

docs/contributing.md
Fixed mangled link and added a short note asking to name resource URLs in predictable manner.
Side note - contributing instructions could specify whether PRs should target the `main` or `wiki-pages` branch of your repository.
=> Update 'Linking resources' section

docs/assets/css/theme.css
A media tag that was left unclosed. The close tag was commented out but the open tag and media was still there.
md css isn't being loaded on some devices, maybe this could be a fix
=> Comment out an open tag without a closing tag

docs/eps/week1.md
Fixed a minor typo in the link to execution-spec-tests( it had github.cosm in it)
=> Fixed broken link to execution-spec-tests

docs/eps/week1.md
[Consensus specs] was linked to the execution-specs Github Repo. Corrected now.
=> Correct Consensus specs Github url

docs/index.html
Currently the wiki forces you to use dark mode although the standard on most websites is to default to light mode or OS default, with sometimes the ability to switch between the two with a button.
I suggest we use the OS default color scheme, and maybe later we can add a switch button if it makes sense.
=> Use OS default color scheme

.github/workflows/md-link.yaml, .github/workflows/md-lint.yaml, .github/workflows/spell-check.yml
Updates spell check actions packages to latest versions, PR for testing
=> Update spell-check action

.github/workflows/spell-check.yml, wordlist.txt
=> 🐞 fix(Spell check): Handle files with spaces

docs/wiki/research/PBS/ePBS.md, wordlist.txt
=> Potuz's correction on PTC and proposer boost and current specs section

docs/wiki/EL/precompiled-contracts.md, wordlist.txt
=> ✨ feat(Precompiles): Updates discussed in week 10

docs/_sidebar.md, docs/wiki/research/PBS/PEPC.md, docs/wiki/research/PBS/PTC.md, docs/wiki/research/PBS/ePBS-Specs.md, docs/wiki/research/PBS/ePBS.md
=> Changed the epbs specs URL, simplified PEPC benefits, disadvantages, and tradeoffs sections into one section

docs/contributing.md
added prerequisites requirement for pages subject to change, in contributing.md
=> added prerequisites requirement for pages subject to change

docs/assets/css/custom.css, notes/wiki_contributors_meeting/2024-05-02_release_plan.md, wordlist.txt
=> 🐞 fix: Content text color

docs/wiki/EL/el-architecture.md
=> Remove duplicated text in EL Architecture 

docs/wiki/research/SSF.md
- [ x] Describe your changes, substitute this text with the information
=> SSF wiki page

docs/wiki/protocol/design-rationale.md
Fixed broken link about Verkle Trees.
=> fix: verkle tree broken link

docs/wiki/EL/data-structures.md, docs/wiki/EL/evm.md
This PR provides an enhanced structure in the EVM learning resources section and mainly include 3 important changes:
- **Enhanced structure for EVM learning resources:** Instead of dropping all resources at once, it categorizes resources based on level of expertise so it's easier for beginners to navigate.
- **Inclusion of some more EVM resources**
- **Inclusion of some well-known EVM CTF Puzzles**
=> Modified EVM Resources section

docs/wiki/pectra-faq.md
Answer some of the questions in Pectra Q&A
=> Partially answer Pectra Q&A

docs/wiki/pectra-faq.md
"Will be" withdrawn sounds like "it has to be". Make it more clear that up to the amount can be withdrawn
=> pectra-faq: partial withdrawal wording

docs/wiki/pectra-faq.md, wordlist.txt
answers the last few open questions in the faq
=> Answers Pectra FAQ questions

docs/wiki/pectra-faq.md, wordlist.txt
some updates to the pectra faq
=> Update Pectra FAQ

docs/eps/intro.md
Updates incorrect file path from node_workshop.md to nodes_workshop.md in week 5 reference link.
=> docs: fix relative path to nodes_workshop.md

docs/_sidebar.md, docs/wiki/research/account-abstraction/eip-7702.md
A stub for EIP-7702. I plan to expand this when I get time.
closes #333
=> ✨ feat: Stub: EIP-7702

docs/wiki/EL/block-production.md
Changes:
a) Line 17: Ambiguous statement about valid transaction
Original: "These transactions are deemed valid and not included in the block."
New: "These transactions are deemed valid and are waiting to be included in a block."
Also, split the run-on sentence.
b) Line 19: Go is a language so written in caps for clarity, also reworded for better clarity.
Original: "We can simplify and emulate the process of constructing blocks, albeit this is specific to the go  with types used in geth. However, the approach is general enough to be adaptable to different clients."
New: "We can simplify and emulate the process of constructing blocks, though this approach is specific to the Go types used in geth. However, the concepts can generally be applied to different clients."
c) Added fullstops …
=> docs: Fix grammar and clarity in block construction documentation

docs/eps/nodes_workshop.md, docs/wiki/CL/cl-clients.md, docs/wiki/EL/block-production.md, docs/wiki/EL/el-clients.md, wordlist.txt
This PR fixes EL Clients table and some typos. It also updates the wordlist.
=> Fix el-clients table

docs/wiki/EL/precompiled-contracts.md
Hi! I updates the broken link replacing EIP-7212 with RIP-7212. The change reflects the proposal's evolution from an Ethereum Improvement Proposal (EIP) to a Rollup Improvement Proposal (RIP).
=> Update broken link precompiled-contracts.md

docs/wiki/testing/incidents.md
This pull request expands the Notable Mainnet Incidents documentation by:
- Adding EthStaker incidents page as a comprehensive reference
- Restructuring content with sections like recent and historical incidents
=> docs: Enhance mainnet incidents documentation with EthStaker reference

docs/wiki/research/PBS/TBHL.md, docs/wiki/research/PBS/mev-boost.md, docs/wiki/research/PBS/pbs.md
- Added more information about `Searchers` in the PBS page.
- Update Block Auction portion to expand on data being exchanged between Relay and Proposer in the `mev-boost` page.
- Fix a broken image link(absolute to relative)
=> feat: update pbs and mev-boost docs

docs/eps/week8-dev.md
The Teku client's github repo is missing in the docs.
=> teku github missing

docs/wiki/EL/el-specs.md
Fixes #406
Added links to the equation numbers in the state collapse function equation table. The equation numbers in the table were incorrect, so I have corrected them from the yellow paper(https://ethereum.github.io/yellowpaper/paper.pdf) (Shanghai version).
=> Add links and fix equation numbers in EL-specs

docs/eps/week1.md
Original link to [Ethereum.org docs](https://ethereum.org/what-is-ethereum) is broken, returning a 404 error. The link was replaced by the equivalente one, with fixed address: https://ethereum.org/en/what-is-ethereum
original creator for review: [@taxmeifyoucan ](https://github.com/taxmeifyoucan)
=> Replace broken link of what-is-ethereum to a equivalent functional one

docs/wiki/pectra-faq.md
sorry about that @taxmeifyoucan
=> happy lint, happy life

docs/wiki/EL/el-architecture.md, wordlist.txt
- added how full sync and snap sync function
- this should probably go in the devp2p section. I'm thinking we make a gh issue to stating to move this context over there once the open devp2p PR's are closed out
=> chore: add sync strategies

docs/wiki/EL/el-specs.md
While reading through the EL specs section of the wiki, gas mechanics are mentioned throughout the page, so I figured it would be useful to have some examples that show how gas is deducted upfront, calcuated during the tsx, and then either burned/sent to proposer/refunded to tsx sender at different stages of the tsx lifecycle.
=> chore: add gas accounting examples
